[manager]
prepend_keymap = [
	{ on = [ "e" ], run = "shell --confirm \"code ./\"", desc = "Open the selected files" },
]
append_keymap = [
 	{ on = [ "g", "p" ], run = "cd /media/common/Dev/Projects/", desc = "Go to the Project directory" },
 	{ on = [ "g", "y" ], run = "cd ~/.config/yazi/", desc = "Go to the yazi directory" },
 	{ on = [ "g", "m" ], run = "cd ~/Movies/", desc = "Go to the Movies directory" },
 	{ on = [ "g", "a" ], run = "cd ~/Anime/", desc = "Go to the Anime directory" },
 	{ on = [ "g", "M" ], run = "cd /media/common/MCA/", desc = "Go to the MCA directory" },
 	{ on = [ "g", "D" ], run = "cd /media/common/Docs/", desc = "Go to the Docs directory" },
 	{ on = [ "g", "b" ], run = "cd ~/dotfiles/", desc = "Go to the dotfiles directory" },
]
