[manager]
prepend_keymap = [
	{ on = [ "e" ], run = "shell --confirm \"code ./\"", desc = "Open the current dir in vscode" },
	{ on = [ "z" ], run = "plugin fzf", desc = "Jump to a directory, or reveal a file using fzf" },
	{ on = [ "Z" ], run = "plugin zoxide", desc = "Jump to a directory using zoxide" },
]
append_keymap = [
 	{ on = [ "g", "p" ], run = "cd /media/common/Dev/Projects/", desc = "Go to the Project directory" },
 	{ on = [ "g", "y" ], run = "cd ~/.config/yazi/", desc = "Go to the yazi directory" },
 	{ on = [ "g", "m" ], run = "cd ~/Movies/", desc = "Go to the Movies directory" },
 	{ on = [ "g", "a" ], run = "cd ~/Anime/", desc = "Go to the Anime directory" },
 	{ on = [ "g", "M" ], run = "cd /media/common/MCA/", desc = "Go to the MCA directory" },
 	{ on = [ "g", "D" ], run = "cd ~/Documents/", desc = "Go to the Docs directory" },
 	{ on = [ "g", "b" ], run = "cd ~/dotfiles/", desc = "Go to the dotfiles directory" },
 	{ on = [ "g", "w" ], run = "cd ~/Pictures/Wallpapers/", desc = "Go to the Wallpapers directory" },
 	{ on = [ "g", "u" ], run = "cd /run/media/sreyas/", desc = "Go to the external media directory" },
 	{ on = [ "g", "/" ], run = "cd /", desc = "Go to the root directory" },
 	{ on = [ "g", "o" ], run = "cd ~/.local/share/Trash/files/", desc = "Go to the trash directory" },
 	{ on = [ "g", "P" ], run = "cd ~/Pictures/", desc = "Go to the Pictures directory" },
 	{ on = [ "g", "C" ], run = "cd /media/common/", desc = "Go to the common drive" },
]
